import AppKit
import CryptoKit
import UniformTypeIdentifiers

/// Pure functions for turning a raw `NSPasteboard` snapshot into a
/// `ClipboardItem`. No side effects, no I/O beyond reading the pasteboard.
enum ItemKindDetector {

    /// Build a ClipboardItem (without persisting it) from the given pasteboard.
    /// Returns nil if the pasteboard is empty / unreadable / a concealed type.
    /// `imageDir` is the directory where image payloads will be saved as PNGs
    /// — only `image` kind writes here.
    static func snapshot(
        pasteboard: NSPasteboard,
        sourceBundle: String?,
        sourceName: String?,
        imageDir: URL
    ) -> ClipboardItem? {
        // Concealed / transient hints — skip immediately.
        let types = pasteboard.types ?? []
        let concealed = Set([
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType"
        ])
        if types.contains(where: { concealed.contains($0.rawValue) }) {
            return nil
        }

        // Priority: image > file > color > url > code > rich text > plain text.
        if let image = pasteboard.readObjects(forClasses: [NSImage.self], options: nil)?.first as? NSImage,
           let item = makeImageItem(image, sourceBundle: sourceBundle, sourceName: sourceName, imageDir: imageDir) {
            return item
        }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           let fileURL = urls.first(where: { $0.isFileURL }) {
            return makeFileItem(fileURL, sourceBundle: sourceBundle, sourceName: sourceName)
        }

        guard let str = pasteboard.string(forType: .string), !str.isEmpty else {
            // RTF without plain string fallback — rare, but cover.
            if let rtf = pasteboard.data(forType: .rtf), let s = String(data: rtf, encoding: .utf8) {
                return makeRichTextItem(s, sourceBundle: sourceBundle, sourceName: sourceName)
            }
            return nil
        }

        let trimmed = str.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty, isColor(trimmed) {
            return makeColorItem(trimmed, sourceBundle: sourceBundle, sourceName: sourceName)
        }
        if !trimmed.isEmpty, isURL(trimmed) {
            return makeURLItem(trimmed, sourceBundle: sourceBundle, sourceName: sourceName)
        }
        if isCode(str) {
            return makeCodeItem(str, sourceBundle: sourceBundle, sourceName: sourceName)
        }
        if pasteboard.types?.contains(.rtf) == true,
           let rtf = pasteboard.data(forType: .rtf),
           let s = String(data: rtf, encoding: .utf8) {
            return makeRichTextItem(s, sourceBundle: sourceBundle, sourceName: sourceName)
        }
        return makeTextItem(str, sourceBundle: sourceBundle, sourceName: sourceName)
    }

    // MARK: detection heuristics

    /// `#RGB` / `#RGBA` / `#RRGGBB` / `#RRGGBBAA` / `rgb(...)` / `rgba(...)`.
    static func isColor(_ s: String) -> Bool {
        let hexPattern = #"^#?[0-9A-Fa-f]{3,8}$"#
        let rgbPattern = #"^rgba?\([^)]+\)$"#
        return s.range(of: hexPattern, options: .regularExpression) != nil
            || s.range(of: rgbPattern, options: .regularExpression) != nil
    }

    /// Strict URL detector — requires an http(s) scheme + host. Avoids matching
    /// plain "github.com" sentences in prose.
    static func isURL(_ s: String) -> Bool {
        guard !s.contains(" "), !s.contains("\n") else { return false }
        guard s.lowercased().hasPrefix("http://") || s.lowercased().hasPrefix("https://") else { return false }
        guard let url = URL(string: s), url.host?.isEmpty == false else { return false }
        return true
    }

    /// Heuristic: ≥ 3 lines AND code-ish character density above 12%.
    /// "Code-ish" = punctuation that's rare in prose: `{}();<>=*&|`.
    static func isCode(_ s: String) -> Bool {
        let lines = s.split(whereSeparator: { $0 == "\n" })
        guard lines.count >= 3 else { return false }
        let total = s.count
        guard total > 0 else { return false }
        let codeishChars: Set<Character> = ["{", "}", "(", ")", ";", "<", ">", "=", "*", "&", "|", "[", "]", "\\"]
        let codey = s.reduce(0) { $0 + (codeishChars.contains($1) ? 1 : 0) }
        return Double(codey) / Double(total) > 0.04
    }

    // MARK: makers

    private static func makeTextItem(_ str: String, sourceBundle: String?, sourceName: String?) -> ClipboardItem {
        let now = Date()
        return ClipboardItem(
            id: UUID(),
            kind: .text,
            contentHash: sha256(str),
            payloadText: str,
            payloadPath: nil,
            preview: previewText(str, max: 200),
            sourceBundle: sourceBundle,
            sourceName: sourceName,
            byteSize: str.utf8.count,
            createdAt: now,
            updatedAt: now,
            pinned: false
        )
    }

    private static func makeRichTextItem(_ rtf: String, sourceBundle: String?, sourceName: String?) -> ClipboardItem {
        let now = Date()
        let preview = previewText(stripRTF(rtf), max: 200)
        return ClipboardItem(
            id: UUID(),
            kind: .richtext,
            contentHash: sha256(rtf),
            payloadText: rtf,
            payloadPath: nil,
            preview: preview,
            sourceBundle: sourceBundle,
            sourceName: sourceName,
            byteSize: rtf.utf8.count,
            createdAt: now,
            updatedAt: now,
            pinned: false
        )
    }

    private static func makeURLItem(_ str: String, sourceBundle: String?, sourceName: String?) -> ClipboardItem {
        let now = Date()
        return ClipboardItem(
            id: UUID(),
            kind: .url,
            contentHash: sha256(str),
            payloadText: str,
            payloadPath: nil,
            preview: str,
            sourceBundle: sourceBundle,
            sourceName: sourceName,
            byteSize: str.utf8.count,
            createdAt: now,
            updatedAt: now,
            pinned: false
        )
    }

    private static func makeColorItem(_ str: String, sourceBundle: String?, sourceName: String?) -> ClipboardItem {
        let now = Date()
        return ClipboardItem(
            id: UUID(),
            kind: .color,
            contentHash: sha256(str.lowercased()),
            payloadText: str,
            payloadPath: nil,
            preview: str,
            sourceBundle: sourceBundle,
            sourceName: sourceName,
            byteSize: str.utf8.count,
            createdAt: now,
            updatedAt: now,
            pinned: false
        )
    }

    private static func makeCodeItem(_ str: String, sourceBundle: String?, sourceName: String?) -> ClipboardItem {
        let now = Date()
        let preview = str.split(whereSeparator: { $0 == "\n" }).prefix(5).joined(separator: "\n")
        return ClipboardItem(
            id: UUID(),
            kind: .code,
            contentHash: sha256(str),
            payloadText: str,
            payloadPath: nil,
            preview: preview,
            sourceBundle: sourceBundle,
            sourceName: sourceName,
            byteSize: str.utf8.count,
            createdAt: now,
            updatedAt: now,
            pinned: false
        )
    }

    private static func makeFileItem(_ url: URL, sourceBundle: String?, sourceName: String?) -> ClipboardItem {
        let now = Date()
        let attrs = try? FileManager.default.attributesOfItem(atPath: url.path)
        let size = (attrs?[.size] as? NSNumber)?.intValue ?? 0
        return ClipboardItem(
            id: UUID(),
            kind: .file,
            contentHash: sha256(url.absoluteString),
            payloadText: nil,
            payloadPath: url,
            preview: url.lastPathComponent,
            sourceBundle: sourceBundle,
            sourceName: sourceName,
            byteSize: size,
            createdAt: now,
            updatedAt: now,
            pinned: false
        )
    }

    private static func makeImageItem(
        _ image: NSImage,
        sourceBundle: String?,
        sourceName: String?,
        imageDir: URL
    ) -> ClipboardItem? {
        // Round-trip → PNG for stable size + dedupe.
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:])
        else { return nil }

        try? FileManager.default.createDirectory(at: imageDir, withIntermediateDirectories: true)
        let id = UUID()
        let dest = imageDir.appendingPathComponent("\(id.uuidString).png")
        guard (try? png.write(to: dest)) != nil else { return nil }

        let now = Date()
        let preview = "\(Int(image.size.width))×\(Int(image.size.height))"
        return ClipboardItem(
            id: id,
            kind: .image,
            contentHash: sha256(png),
            payloadText: nil,
            payloadPath: dest,
            preview: preview,
            sourceBundle: sourceBundle,
            sourceName: sourceName,
            byteSize: png.count,
            createdAt: now,
            updatedAt: now,
            pinned: false
        )
    }

    // MARK: helpers

    private static func sha256(_ s: String) -> String {
        sha256(Data(s.utf8))
    }
    private static func sha256(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    private static func previewText(_ s: String, max: Int) -> String {
        let collapsed = s.replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\t", with: " ")
        if collapsed.count <= max { return collapsed }
        let end = collapsed.index(collapsed.startIndex, offsetBy: max)
        return collapsed[..<end] + "…"
    }

    /// Very rough RTF-to-text — enough for a preview line.
    private static func stripRTF(_ rtf: String) -> String {
        guard let data = rtf.data(using: .utf8),
              let attr = try? NSAttributedString(
                data: data,
                options: [.documentType: NSAttributedString.DocumentType.rtf],
                documentAttributes: nil
              )
        else { return rtf }
        return attr.string
    }
}
